//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Component.cpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#include "Component.hpp"

int Component::GetId() {
	return this->id;
}

void Component::SetId(int id) {
	this->id= id;
}

double Component::GetBandwidth() {
	return this->bandwidth;
}

void Component::SetBandwidth(double bw) {
	this->bandwidth= bandwidth;
}

std::string Component::GetName(){
	return this->name;
}

void Component::SetName(std::string){
	this->name= name;
}

string Component::GetStatus() {
	return this->status;
}

void Component::CalculateStatus(){
	//this function communicates wityh the provisionning module
}

void Component::SetStatus(string status){
	this->status=status;
}

