//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Component.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#if !defined(_COMPONENT_H)
#define _COMPONENT_H
#include <iostream>
#include <string>
using namespace std;

class Component {
public:
	int GetId();
	void SetId(int);
	double GetBandwidth();
	void SetBandwidth(double);
	std::string GetName();
	void SetName(std::string);
	string GetStatus();
	void SetStatus(string);
	void CalculateStatus();
	void Display();
protected:
	int id;
	std::string name;
	string status;
	double bandwidth;
};

#endif  //_COMPONENT_H
