//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Link.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#if !defined(_LINK_H)
#define _LINK_H

#include "Component.hpp"

class Link : public Component {
};

#endif  //_LINK_H
