//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : mapping.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#if !defined(_MAPPING_H)
#define _MAPPING_H
#include"Request.hpp"
#include"Substrate_network.hpp"

class mapping {
public:
	mapping(class Request*);
	double GetAvailability();
	int GetStateMapping();
	void SetStateMapping(int);
	double GetMapTime();
	void SetMapTime(double);
	Request* GetRequest();
	void SetRequest(Request*);
	bool mapp(Substrate_network*);
	void displayMapp();
	void displayMappNode();
	void displayMappPath();
	double avaiMapp();
	double avaiMappNode();
	double avaiMappPath();
	void ApplyBestMapping(int *,std::list<int> *,int*,Substrate_network*);
	void ApplyBestMappingNodes(int *,Substrate_network*);
	void ApplyBestMappingPaths(std::list<int> *,int*,Substrate_network*);//path_mapp[] path_length[]
	bool Migrate(int,Substrate_network*);// migrate a node from Substrate node to another
protected:
	int id;
	int stateMapping;
	double mapTime;
	double availability;
	class Request * request;
};

#endif  //_MAPPING_H
