//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Node.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//

#if !defined(_NODE_H)
#define _NODE_H

#include "Component.hpp"
#include "Link.hpp"

class Node: public Component {
public:
	int GetType();
	void SetType(int);
	double GetMemory();
	void SetMemory(double);
	double GetUsedMemory();
	double GetRestMemory();
	double GetCpu();
	void SetCpu(double);
	double GetUsedCpu();
	double GetRestCpu();
	double GetDisk();
	void SetDisk(double);
	double GetUsedDisk();
	double GetRestDisk();
	Link *from;
protected:
	int type;
	double memory;
	double cpu;
	double disk;
};

#endif  //_NODE_H
