//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Path.cpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#include "Path.hpp"
Path::Path(int id,Virtual_node * from,Virtual_node * to,double bw){
	this->id=id;
	this->from=from;
	this->to=to;
	this->bandwidth=bw;
}

Path::Path(int id,int from_id,Virtual_node * from,int to_id,Virtual_node * to,double bw){
	this->id=id;
	this->from_id=from_id;
	this->from=from;
	this->to_id=to_id;
	this->to=to;
	this->bandwidth=bw;
}

Path::Path(int id,string name, int from_id,Virtual_node * from,int to_id,Virtual_node * to,double bw){
	this->id=id;
	this->name=name;
	this->from_id=from_id;
	this->from=from;
	this->to_id=to_id;
	this->to=to;
	this->bandwidth=bw;
}

std::list<Substrate_link> * Path::GetSubstrateLinks() {
	return &this->substrateLinks;
}

int Path::GetLength(){
	return this->length;
}

void Path::SetLength(int length){
	this->length=length;
}

Virtual_node* Path::GetSourceNode() {
	return this->from;
}

Virtual_node* Path::GetDestinationNode() {
	return this->to;
}

int Path::GetSourceNode_id() {
	return this->from_id;
}

int Path::GetDestinationNode_id() {
	return this->to_id;
}
