//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Substrate_link.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#if !defined(_SUBSTRATE_LINK_H)
#define _SUBSTRATE_LINK_H

#include "Link.hpp"
#include "Substrate_node.hpp"
#include "Path.hpp"
#include "def.h"

class Substrate_link : public Link {
public:
	Substrate_link();
	Substrate_link(int id, Substrate_node * from, Substrate_node * to, double bw, double avai);
	void SetAvailability(double);
	double GetAvailability();
	Substrate_node * GetSourceNode();
	int GetSourceNode_id();
	Substrate_node * GetDestinationNode();
	int GetDestinationNode_id();
	std::list<class Path>* GetEmbeddedPaths();
	bool removeEmbeddedPath(Path*);
	void DisplayEmdeddedPaths();
    double GetUsedBandwidth();
	double GetRestBandwidth();
	void Display();
private:
	double availability;
	Substrate_node * from;
	int from_id;
	Substrate_node * to;
	int to_id;
	std::list<Path> embeddedPaths;
};

#endif  //_SUBSTRATE_LINK_H
