//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : SAVI/VDCPlanner
//  @ File Name : Substrate_node.hpp
//  @ Date : 17/04/2013
//  @ Author : Maissa Jabri
//
//


#if !defined(_SUBSTRATE_NETWORK_H)
#define _SUBSTRATE_NETWORK_H
#include <iostream> 
#include <list> 
#include "Substrate_node.hpp"
#include "Substrate_link.hpp"
#include "Sub_node_type.h"
#include "AdjNode.hpp"

using namespace std;

class Substrate_network {
private:
	double id;
	int numberNodes;;
	std::list<class Sub_node_type> types; 
	std::list<class Substrate_link> links;
	AdjNode ** adjMatrix;
public:
	Substrate_network(void);
	Substrate_network(int);
	~Substrate_network(void);
	int GetId();
	void SetId(int);
	int GetNumberNodes();
	void SetNumberNodes(int);
	void ComputeAdjMatrix();
	void DisplayAdjMatrix();
	AdjNode ** GetAdjMatrix();
	Sub_node_type * GetTypeById(int);
	std::list<class Sub_node_type>* GetTypes();
	Substrate_node* GetNodeByName(string);
	Substrate_node* GetNodeById(int);
	Substrate_link* GetLinkById(int);
	std::list<class Substrate_link>* GetSubstrateLinks();
	Substrate_link * GetLinkByFromTo(int,int);
	void DisplaySubstrate();
	void DisplaySubstrateEmbedding();
};

#endif  //_SUBSTRATE_NETWORK_H
